# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keys', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbConfiguration',
            fields=[
                ('Id_Configuration', models.AutoField(db_column='Id_Configuration', primary_key=True, serialize=False)),
                ('dataConfiguration', models.TextField(db_column='dataConfiguration')),
                ('key', models.ForeignKey(db_column='Id_Key', on_delete=django.db.models.deletion.CASCADE, to='keys.tbkey')),
                ('levelKey', models.ForeignKey(db_column='Id_LevelKey', on_delete=django.db.models.deletion.CASCADE, to='generals.tblevelkeys')),
            ],
            options={
                'db_table': 'Tb_Configuration',
                'managed': True,
            },
        ),
    ]
