# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbAplication',
            fields=[
                ('Id_Aplication', models.AutoField(db_column='Id_Aplication', primary_key=True, serialize=False)),
                ('nameAplication', models.CharField(db_column='nameAplication', max_length=255)),
            ],
            options={
                'db_table': 'Tb_Aplication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbSection',
            fields=[
                ('Id_Section', models.AutoField(db_column='Id_Section', primary_key=True, serialize=False)),
                ('nameSection', models.CharField(db_column='nameSection', max_length=255)),
                ('aplication', models.ForeignKey(db_column='Id_Aplication', on_delete=django.db.models.deletion.CASCADE, to='aplications.tbaplication')),
            ],
            options={
                'db_table': 'Tb_Section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbModule',
            fields=[
                ('Id_Module', models.AutoField(db_column='Id_Module', primary_key=True, serialize=False)),
                ('nameModule', models.CharField(db_column='nameModule', max_length=255)),
                ('aplication', models.ForeignKey(db_column='Id_Aplication', on_delete=django.db.models.deletion.CASCADE, to='aplications.tbaplication')),
            ],
            options={
                'db_table': 'Tb_Module',
                'managed': True,
            },
        ),
    ]
