# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0002_tbaplication_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbmodule',
            name='aplication',
        ),
    ]
