# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0003_remove_tbmodule_aplication'),
        ('peopleModules', '0002_remove_tbpeoplemodule_module_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbModule',
        ),
    ]
