# Generated by Django 4.1.7 on 2023-02-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packageConfig', '0001_initial'),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbPackageConfigKeys',
            fields=[
                ('Id_PackageConfigKeys', models.AutoField(db_column='Id_PackageConfigKeys', primary_key=True, serialize=False)),
                ('keys', models.ForeignKey(db_column='Id_Key', on_delete=django.db.models.deletion.CASCADE, to='keys.tbkey')),
                ('packageConfig', models.ForeignKey(db_column='Id_PackageConfig', on_delete=django.db.models.deletion.CASCADE, to='packageConfig.tbpackageconfig')),
            ],
            options={
                'db_table': 'Tb_PackageConfigKeys',
                'managed': True,
            },
        ),
    ]
