# Generated by Django 4.1.7 on 2023-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageConfigKeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbpackageconfigkeys',
            name='organization',
            field=models.IntegerField(db_column='Id_Configuration', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbpackageconfigkeys',
            name='site',
            field=models.IntegerField(db_column='Id_Site', default=0),
        ),
        migrations.AddField(
            model_name='tbpackageconfigkeys',
            name='zone',
            field=models.IntegerField(db_column='Id_Zone', default=0),
        ),
    ]
