# Generated by Django 4.1.7 on 2023-02-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
        ('packageConfigKeys', '0002_tbpackageconfigkeys_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbpackageconfigkeys',
            name='deviceType',
            field=models.ForeignKey(db_column='Id_DeviceType', default=1, on_delete=django.db.models.deletion.CASCADE, to='generals.tbdevicetype'),
            preserve_default=False,
        ),
    ]
