# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDevice',
            fields=[
                ('Id_Device', models.AutoField(db_column='Id_Device', primary_key=True, serialize=False)),
                ('nameDevice', models.CharField(db_column='nameDevice', max_length=255)),
                ('tokenDevice', models.CharField(db_column='tokenDevice', max_length=255)),
                ('creationDateDevice', models.DateTimeField(auto_now_add=True, db_column='creationDateDevice')),
                ('deviceType', models.ForeignKey(db_column='Id_DeviceType', on_delete=django.db.models.deletion.CASCADE, to='generals.tbdevicetype')),
                ('hwPlatform', models.ForeignKey(db_column='Id_HwPlatform', on_delete=django.db.models.deletion.CASCADE, to='generals.tbhwplatform')),
                ('organization', models.ForeignKey(db_column='Id_Organization', on_delete=django.db.models.deletion.CASCADE, to='organizations.tborganization')),
                ('os', models.ForeignKey(db_column='Id_Os', on_delete=django.db.models.deletion.CASCADE, to='generals.tbos')),
            ],
            options={
                'db_table': 'Tb_Device',
                'managed': True,
            },
        ),
    ]
