# Generated by Django 4.1.7 on 2023-02-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbdevice',
            name='isActive',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
    ]
