# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peoples', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbToken',
            fields=[
                ('id_Token', models.AutoField(db_column='Id_Token', primary_key=True, serialize=False)),
                ('valueToken', models.CharField(db_column='valueToken', max_length=255, null=True)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('Id_Owner', models.IntegerField(db_column='Id_Owner')),
                ('people', models.ForeignKey(db_column='Id_People', on_delete=django.db.models.deletion.CASCADE, to='peoples.tbpeople')),
                ('tokenType', models.ForeignKey(db_column='Id_TokenType', on_delete=django.db.models.deletion.CASCADE, to='generals.tbtokentype')),
            ],
            options={
                'db_table': 'Tb_Token',
                'managed': True,
            },
        ),
    ]
