# Generated by Django 4.1.7 on 2023-02-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbtoken',
            name='Id_Owner',
        ),
    ]
