# Generated by Django 4.1.7 on 2023-02-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblocation',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tblocation',
            table='Tb_Location',
        ),
    ]
