# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbSetting',
            fields=[
                ('Id_Setting', models.AutoField(db_column='Id_Setting', primary_key=True, serialize=False)),
                ('dataSetting', models.TextField(db_column='dataSetting')),
                ('device', models.ForeignKey(db_column='Id_Device', on_delete=django.db.models.deletion.CASCADE, to='devices.tbdevice')),
                ('settingType', models.ForeignKey(db_column='Id_SettingType', on_delete=django.db.models.deletion.CASCADE, to='generals.tbsettingtype')),
            ],
            options={
                'db_table': 'Tb_Setting',
                'managed': True,
            },
        ),
    ]
