# Generated by Django 4.1.7 on 2023-02-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_tbsetting_namesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbsetting',
            name='nameSetting',
        ),
    ]
