# Generated by Django 4.1.7 on 2023-02-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageConfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbpackageconfig',
            name='namePackage',
            field=models.CharField(db_column='namePackage', max_length=255),
        ),
    ]
