# Generated by Django 4.1.7 on 2023-02-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packageConfig', '0002_alter_tbpackageconfig_namepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpackageconfig',
            name='deviceType',
        ),
        migrations.RemoveField(
            model_name='tbpackageconfig',
            name='site',
        ),
        migrations.RemoveField(
            model_name='tbpackageconfig',
            name='zone',
        ),
    ]
