# Generated by Django 4.1.7 on 2023-03-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplications', '0003_remove_tbmodule_aplication'),
        ('peopleModules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbpeoplemodule',
            name='module',
        ),
        migrations.AddField(
            model_name='tbpeoplemodule',
            name='aplication',
            field=models.ForeignKey(db_column='Id_Aplication', default=1, on_delete=django.db.models.deletion.CASCADE, to='aplications.tbaplication'),
            preserve_default=False,
        ),
    ]
