# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbKey',
            fields=[
                ('Id_Key', models.AutoField(db_column='Id_Key', primary_key=True, serialize=False)),
                ('nameKey', models.CharField(db_column='nameKey', max_length=255)),
                ('organization', models.ForeignKey(db_column='Id_Organization', on_delete=django.db.models.deletion.CASCADE, to='organizations.tborganization')),
            ],
            options={
                'db_table': 'Tb_Key',
                'managed': True,
            },
        ),
    ]
