# Generated by Django 4.1.7 on 2023-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbkey',
            name='valueKey',
            field=models.TextField(db_column='valueKey', default={'AuthenticationRapi': {'client_id': '62470945-839d-4acb-81db-d7db8440ad4f', 'client_secret': 'AW0igYe8kndkjcckiJ69DffU9D54f7fgy1rpJgFeCRc=', 'url': 'http://104.217.253.100:5000'}, 'AuthenticationTOTP': [{'Id': 1, 'Value': 'KBCVIX2UIVBU4SKDJ4YDC==='}, {'Id': 2, 'Value': 'KBCVIX2UIVBU4SKDJ4YDE==='}, {'Id': 3, 'Value': 'KBCVIX2UIVBU4SKDJ4YDG==='}, {'Id': 4, 'Value': 'KBCVIX2UIVBU4SKDJ4YDI==='}, {'Id': 5, 'Value': 'IRCVGQKSKJHUYTCPL5IEKVA='}, {'Id': 6, 'Value': 'KNHVAT2SKRCV6USFJVHVITZR'}, {'Id': 7, 'Value': 'KNHVAT2SKRCV6USFJVHVITZS'}, {'Id': 8, 'Value': 'KNHVAT2SKRCV6USFJVHVITZT'}, {'Id': 9, 'Value': 'KNHVAT2SKRCV6USFJVHVITZU'}, {'Id': 10, 'Value': 'KBCVIX2DJ5HVERCJJZAUGSKPJYYQ===='}, {'Id': 11, 'Value': 'KBCVIX2DJ5HVERCJJZAUGSKPJYZA===='}, {'Id': 12, 'Value': 'KBCVIX2EIVGU6Q2J'}], 'suscriptions': {'Services': [{'TransactionService': {'mqttData': {'SuscriptionType': 'Local', 'topic': 'transaction'}}}], 'mqttLocalServer': {'domain': 'pet', 'host': '172.107.174.60', 'login': 'ci24', 'password': 'Controles1*', 'port': 8001, 'timeout': 10}}}),
            preserve_default=False,
        ),
    ]
