# Generated by Django 4.1.7 on 2023-02-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_tbkey_devicetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbkey',
            name='deviceType',
        ),
    ]
