# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbZone',
            fields=[
                ('Id_Zone', models.AutoField(db_column='Id_Zone', primary_key=True, serialize=False)),
                ('nameZone', models.CharField(db_column='nameZone', max_length=255)),
                ('site', models.ForeignKey(db_column='Id_Site', on_delete=django.db.models.deletion.CASCADE, to='sites.tbsite')),
            ],
            options={
                'db_table': 'Tb_Zone',
                'managed': True,
            },
        ),
    ]
