# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('aplications', '0001_initial'),
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbPermission',
            fields=[
                ('Id_Permission', models.AutoField(db_column='Id_Permission', primary_key=True, serialize=False)),
                ('dataPermission', models.TextField(db_column='dataPermission')),
                ('aplication', models.ForeignKey(db_column='Id_Aplication', on_delete=django.db.models.deletion.CASCADE, to='aplications.tbaplication')),
                ('organization', models.ForeignKey(db_column='Id_Organization', on_delete=django.db.models.deletion.CASCADE, to='organizations.tborganization')),
                ('people', models.ForeignKey(db_column='id_People', on_delete=django.db.models.deletion.CASCADE, to='peoples.tbpeople')),
            ],
            options={
                'db_table': 'Tb_Permission',
                'managed': True,
            },
        ),
    ]
