# Generated by Django 4.1.7 on 2023-02-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbOrganization',
            fields=[
                ('Id_Organization', models.AutoField(db_column='Id_Organization', primary_key=True, serialize=False)),
                ('nameOrganization', models.CharField(db_column='nameOrganization', max_length=255)),
                ('taxIdOrganization', models.CharField(db_column='taxIdOrganization', max_length=255)),
                ('addressOrganization', models.CharField(db_column='addressOrganization', max_length=255)),
                ('contactEmailOrganization', models.CharField(db_column='contactEmailOrganization', max_length=255)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('city', models.ForeignKey(db_column='Id_City', on_delete=django.db.models.deletion.CASCADE, to='generals.tbcity')),
            ],
            options={
                'db_table': 'Tb_Organization',
                'managed': True,
            },
        ),
    ]
